<?php

/**
 * @file
 * Code for the hr_indicator_data feature.
 */

include_once 'hr_indicator_data.features.inc';

/**
 * Implements hook_menu().
 */
function hr_indicator_data_menu() {
  $items['crf/indicator-data/table'] = array(
    'title' => 'Indicator Data',
    'page callback' => 'hr_indicator_data_table',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['crf/indicator-data/graph'] = array(
    'title' => 'Graph',
    'page callback' => 'hr_indicator_data_graph',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hr_indicator_data_form_indicator_data_node_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('entityconnect') && isset($form_state['#entityconnect_child_form'])) {
    $indicator_data_batch_input = $form_state['#entityconnect_child_form']->data['form_state']['input'];
    $form['field_cluster']['und']['#default_value'] = $indicator_data_batch_input['field_cluster']['und'];
  }
}

function hr_indicator_data_table() {
  $output = '';
  $output .= l('Graph', 'crf/indicator-data/graph');
  $output .= views_embed_view('indicator_data', 'table');
  return $output;
}

function hr_indicator_data_graph() {
  $output = '';
  $output .= l('Table', 'crf/indicator-data/table');
  $output .= views_embed_view('indicator_data', 'graph');
  return $output;
}

